### ISSUE TITLE
wxFormBuilder Error pops up when using wxTextCtrl with wxTE_RICH style flag

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#219]
In wxFormBuilder v3.5 - beta

When having a wxTextCtrl with flag wxTE_RICH or wxTE_RICH2 set under object properties style, an 'wxFormBuilder Error' dialog with message 'ObjectBase is NULL! <C:/ ... /wxFormBuilder/src/rad/wxfbmanager.cpp,167>' pops up.

Without the flags set, everything is ok.

Reported by: robekras

**Comment by timkostka** [comment]
This is still a bug in the v3.9.0 version.  Same steps to reproduce, same workaround: either ignore the error or edit the FBP directly and remove the <font> tag.

Error message:
12:29:37: No corresponding ObjectBase for wxObject. Name: wxTextCtrl
12:29:37: ObjectBase is NULL! <../../../src/rad/wxfbmanager.cpp,168>
12:29:37: No corresponding ObjectBase for wxObject. Name: wxTextCtrl
12:29:37: ObjectBase is NULL! <../../../src/rad/wxfbmanager.cpp,168>

**Comment by sodevel** [comment]
For some strange reason this seems to got fixed by #565

**Comment by rkcity** [comment]
not fix. 
this symptom still occur for me with commit 50fee97f296e0e3f6147f9a12c1c8ea3d0c23b78

**Comment by sodevel** [comment]
It does not happen for me, no matter which RICH style i use and what i modify. Maybe it is not related to wxFB itself but wxWidgets? I am using wxWidgets https://github.com/wxWidgets/wxWidgets/commit/ed8fd1893a2c53ca4fdde763c59ba5a9c2d3ba1e.

**Comment by rkcity** [comment]
i build a debug version and trace the logger:
```
## Create TextCtrl
mainframe.cpp@789 OnObjectCreated: MainFrame::OnObjectCreated
appdata.cpp@2978 NotifyEvent: event: wxEVT_FB_OBJECT_SELECTED
mainframe.cpp@710 OnObjectSelected: MainFrame::OnObjectSelected

## Change TextCtrl Font Attribute 
appdata.cpp@2978 NotifyEvent: event: wxEVT_FB_PROPERTY_MODIFIED
call m_wxobjects.insert. insert obj ClassName: wxBoxSizer
call m_wxobjects.insert. insert obj ClassName: wxObject
call m_wxobjects.insert. insert obj ClassName: wxTextCtrl
find in m_wxobjects : wxObject <../../../src/rad/designer/visualeditor.cpp,186>
find in m_wxobjects : wxObject <../../../src/rad/designer/visualeditor.cpp,186>
find in m_wxobjects : wxObject <../../../src/rad/designer/visualeditor.cpp,186>
find in m_wxobjects : wxTextCtrl <../../../src/rad/designer/visualeditor.cpp,186>

## Set TextCtrl Style: wxTE_Rich
appdata.cpp@2978 NotifyEvent: event: wxEVT_FB_PROPERTY_MODIFIED
call m_wxobjects.insert. insert obj ClassName: wxBoxSizer
call m_wxobjects.insert. insert obj ClassName: wxObject
  ## Strange Here
  find in m_wxobjects : wxTextCtrl <../../../src/rad/designer/visualeditor.cpp,186>
  02:58:18: Error: No corresponding ObjectBase for wxObject. Name: wxTextCtrl
  02:58:18: Error: ObjectBase is NULL! <../../../src/rad/wxfbmanager.cpp,168>
  find in m_wxobjects : wxTextCtrl <../../../src/rad/designer/visualeditor.cpp,186>
  02:58:18: Error: No corresponding ObjectBase for wxObject. Name: wxTextCtrl
  02:58:18: Error: ObjectBase is NULL! <../../../src/rad/wxfbmanager.cpp,168>
  ## End
call m_wxobjects.insert. insert obj ClassName: wxTextCtrl
find in m_wxobjects : wxObject <../../../src/rad/designer/visualeditor.cpp,186>
find in m_wxobjects : wxObject <../../../src/rad/designer/visualeditor.cpp,186>
find in m_wxobjects : wxObject <../../../src/rad/designer/visualeditor.cpp,186>
find in m_wxobjects : wxTextCtrl <../../../src/rad/designer/visualeditor.cpp,186>
```

the strange thing is:
it invoke `VisualEditor::GetObjectBase()` to find out `wxTextCtrl` before invoke `m_wxobjects.insert()` to insert `wxTextCtrl` while TextCtrl has Rich or Rich2 attribute and then setup font name.
set Rich/Rich2 after font name has same situation

**Comment by sodevel** [comment]
I repeat my question, which wxWidgets version are you using? I cannot reproduce this any more with the version i am using.

**Comment by Kvaz1r** [comment]
I can reproduce the error with wxWidgets 3.0 (from default package i.e. mingw-w64-i686-wxWidgets )

**Comment by sodevel** [comment]
Then this looks like this is another issue on the list of issues that will fix themself by using a recent wxWidgets version 😃

**Comment by rkcity** [comment]
yes, my environment is under msys2 and the package of wxWidgets is version 3.0.4
i'll try to build the latest version of wxWidgets on msys2
thanks a lot : )

**Comment by Alexander3XL** [comment]
Hello! I found a solution: just leave the value empty.
The error  reproduced on my arch linux machine with wxFormBuilder 3.9.0.
For wxTextCtrl needs:
1) set 'value' to any text;
2) set 'style' to 'wxTE_MULTILINE';
3) set 'font->family' to 'teletype'.
Ocures error!
12:19:16: No corresponding ObjectBase for wxObject. Name: wxTextCtrl
12:19:16: ObjectBase is NULL! <../../../src/rad/wxfbmanager.cpp,168>
12:19:16: No corresponding ObjectBase for wxObject. Name: wxTextCtrl
12:19:16: ObjectBase is NULL! <../../../src/rad/wxfbmanager.cpp,168>
